# Generated by Django 3.2.18 on 2023-04-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
    ]
